/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SessionBuilderWrapper {
  constructor(ourIdentityKey: KeyPairObject)
  initOutgoing(device: DeviceBundleObject): string
  initIncoming(message: PreKeyWhisperMessageObject, preKeyPair: KeyPairObject | undefined | null, signedPreKeyPair: KeyPairObject): string
}

export declare class SessionCipherWrapper {
  constructor(ourIdentityKey: KeyPairObject, ourRegistrationId: number)
  encrypt(sessionJson: string, data: Buffer): EncryptResult
  decryptWhisperMessage(sessionJson: string, message: Buffer): Buffer
}

export declare class SessionRecordWrapper {
  constructor()
  serialize(): string
  getVersion(): string
  haveOpenSession(): boolean
  removeOldSessions(): void
  deleteAllSessions(): void
}

export interface BaseKeyTypeEnum {
  ours: number
  theirs: number
}

export declare function calculateAgreement(pubKey: Buffer, privKey: Buffer): Buffer

export declare function calculateMac(key: Buffer, data: Buffer): Buffer

export interface ChainTypeEnum {
  sending: number
  receiving: number
}

export interface CreateKeyPair {
  pubKey: Buffer
  privKey: Buffer
}

export declare function createSenderKey(keyId: number, iteration: number, chainKey: Buffer, signingKeyPublic: Buffer, signingKeyPrivate?: Buffer | undefined | null): Buffer

export declare function createSenderKeyDistributionMessage(keyId: number, iteration: number, chainKey: Buffer, signingKey: Buffer): Buffer

export declare function curve25519Sign(privkey: Buffer, msg: Buffer): Buffer

export declare function decryptData(key: Buffer, data: Buffer, iv: Buffer): Buffer

export declare function deriveSecrets(input: Buffer, salt: Buffer, info: Buffer, chunks: number): Array<Buffer>

export declare function deserializeSenderKeyRecordJson(base64Str: string): Buffer

export interface DeviceBundleObject {
  identityKey: Buffer
  registrationId: number
  signedPreKey: SignedPreKeyBundle
  preKey?: PreKeyBundle
}

export declare function encryptData(key: Buffer, data: Buffer, iv: Buffer): Buffer

export interface EncryptResult {
  messageType: number
  body: Buffer
  registrationId: number
}

export declare function generateKeyPair(): CreateKeyPair

export declare function generatePreKey(keyId: number): GeneratePreKey

export interface GeneratePreKey {
  pubKey: Buffer
  privKey: Buffer
  keyId: number
}

export declare function generateRegistrationId(): number

export declare function getBaseKeyType(): BaseKeyTypeEnum

export declare function getChainType(): ChainTypeEnum

export declare function groupDecryptMessage(senderKeyRecordBytes: Buffer, ciphertext: Buffer): Buffer

export declare function groupEncryptMessage(senderKeyRecordBytes: Buffer, plaintext: Buffer): Buffer

export declare function hash(data: Buffer): Buffer

export interface JsKeyPair {
  pubKey: Buffer
  privKey: Buffer
}

export declare function keyPair(privKey: Buffer): JsKeyPair

export interface KeyPairObject {
  pubKey: Buffer
  privKey: Buffer
}

export declare function parseSenderKeyDistributionMessage(serialized: Buffer): SenderKeyDistributionMessageResult

export interface PreKeyBundle {
  keyId: number
  publicKey: Buffer
}

export interface PreKeyWhisperMessageObject {
  identityKey: Buffer
  registrationId: number
  baseKey: Buffer
  preKeyId?: number
  signedPreKeyId: number
}

export declare function processSenderKeyDistribution(existingRecordBytes: Buffer, distributionMessage: Buffer): Buffer

export interface SenderKeyDistributionMessageResult {
  id: number
  iteration: number
  chainKey: Buffer
  signingKey: Buffer
}

export declare function serializeSenderKeyRecordJson(recordBytes: Buffer): string

export declare function sharedSecret(pubKey: Buffer, privKey: Buffer): Buffer

export interface SignedPreKeyBundle {
  keyId: number
  publicKey: Buffer
  signature: Buffer
}

export declare function verify(sig: Buffer, pubKey: Buffer, message: Buffer): boolean

export declare function verifyMac(key: Buffer, data: Buffer, expectedMac: Buffer, length: number): void

export declare function verifySignature(pubKey: Buffer, message: Buffer, sig: Buffer, isInit: boolean): boolean
