/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function calculateAgreement(pubKey: Buffer, privKey: Buffer): Buffer

export declare function createKeyPair(privKey: Buffer): object

export declare function generateKeyPair(): object

export declare function groupEncrypt(iteration: number, chainKey: Buffer, plaintext: Buffer): Buffer

export declare function keyPair(privKey: Buffer): object

export declare function sharedSecret(pubKey: Buffer, privKey: Buffer): Buffer

export declare function verify(sig: Buffer, pubKey: Buffer, message: Buffer): boolean

export declare function verifySignature(pubKey: Buffer, message: Buffer, sig: Buffer, isInit: boolean): boolean
