/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function calculateAgreement(pubKey: Buffer, privKey: Buffer): Buffer

export declare function calculateMac(key: Buffer, data: Buffer): Buffer

export declare function createKeyPair(privKey: Buffer): CreateKeyPair

export interface CreateKeyPair {
  pubKey: Buffer
  privKey: Buffer
}

export declare function curve25519Sign(privkey: Buffer, msg: Buffer): Buffer

export declare function decryptData(key: Buffer, data: Buffer, iv: Buffer): Buffer

export declare function deriveSecrets(input: Buffer, salt: Buffer, info: Buffer, chunks: number): Array<Buffer>

export declare function encryptData(key: Buffer, data: Buffer, iv: Buffer): Buffer

export declare function encryptWhisperMessage(messageKey: Buffer, plaintext: Buffer, ephemeralKey: Buffer, counter: number, previousCounter: number | undefined | null, remoteIdentity: Buffer, data: EncryptWhisperMessage): Buffer

export interface EncryptWhisperMessage {
  ourIdentity: Buffer
  version: number
}

export declare function fillMessageKeys(chainKey: Buffer, currentCounter: number, targetCounter: number): FillMessageKeysResult

export interface FillMessageKeysResult {
  chainKey: Buffer
  counter: number
  messageKeys: Array<Buffer>
}

export declare function generateKeyPair(): CreateKeyPair

export declare function generatePreKey(keyId: number): GeneratePreKey

export interface GeneratePreKey {
  pubKey: Buffer
  privKey: Buffer
  keyId: number
}

export declare function generateRegistrationId(): number

export declare function generateSignedPreKey(identityPrivKey: Buffer, identityPubKey: Buffer, signedPreKeyId: number): GenerateSignedPreKey

export interface GenerateSignedPreKey {
  keyId: number
  pubKey: Buffer
  signature: Buffer
}

export declare function hash(data: Buffer): Buffer

export interface JsKeyPair {
  pubKey: Buffer
  privKey: Buffer
}

export declare function keyPair(privKey: Buffer): JsKeyPair

export declare function sharedSecret(pubKey: Buffer, privKey: Buffer): Buffer

export declare function verify(sig: Buffer, pubKey: Buffer, message: Buffer): boolean

export declare function verifyMac(key: Buffer, data: Buffer, expectedMac: Buffer, length: number): void

export declare function verifySignature(pubKey: Buffer, message: Buffer, sig: Buffer, isInit: boolean): boolean
