// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderKeyMessage {
    #[prost(uint32, optional, tag="1")]
    pub id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="2")]
    pub iteration: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="3")]
    pub ciphertext: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderKeyDistributionMessage {
    #[prost(uint32, optional, tag="1")]
    pub id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="2")]
    pub iteration: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="3")]
    pub chain_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="4")]
    pub signing_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderChainKey {
    #[prost(uint32, optional, tag="1")]
    pub iteration: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="2")]
    pub seed: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderMessageKey {
    #[prost(uint32, optional, tag="1")]
    pub iteration: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="2")]
    pub seed: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderSigningKey {
    #[prost(bytes="vec", optional, tag="1")]
    pub public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="2")]
    pub private: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderKeyStateStructure {
    #[prost(uint32, optional, tag="1")]
    pub sender_key_id: ::core::option::Option<u32>,
    #[prost(message, optional, tag="2")]
    pub sender_chain_key: ::core::option::Option<SenderChainKey>,
    #[prost(message, optional, tag="3")]
    pub sender_signing_key: ::core::option::Option<SenderSigningKey>,
    #[prost(message, repeated, tag="4")]
    pub sender_message_keys: ::prost::alloc::vec::Vec<SenderMessageKey>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderKeyRecordStructure {
    #[prost(message, repeated, tag="1")]
    pub sender_key_states: ::prost::alloc::vec::Vec<SenderKeyStateStructure>,
}
