// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRecord {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, optional, tag = "2")]
    pub current: ::core::option::Option<Session>,
    #[prost(message, repeated, tag = "3")]
    pub archived: ::prost::alloc::vec::Vec<Session>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    #[prost(bytes = "vec", tag = "1")]
    pub local_identity_public: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub remote_identity_public: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub local_registration_id: u32,
    #[prost(uint32, tag = "4")]
    pub remote_registration_id: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub root_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "6")]
    pub previous_counter: u32,
    #[prost(message, optional, tag = "7")]
    pub sender_chain: ::core::option::Option<SenderChain>,
    #[prost(message, repeated, tag = "8")]
    pub receiver_chains: ::prost::alloc::vec::Vec<ReceiverChain>,
    #[prost(message, optional, tag = "9")]
    pub pending_pre_key: ::core::option::Option<PendingPreKey>,
    #[prost(bytes = "vec", tag = "10")]
    pub alice_base_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "11")]
    pub metadata: ::core::option::Option<SessionMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderChain {
    #[prost(bytes = "vec", tag = "1")]
    pub ratchet_public: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub ratchet_private: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub chain_key: ::core::option::Option<ChainKey>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiverChain {
    #[prost(bytes = "vec", tag = "1")]
    pub ratchet_public: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub chain_key: ::core::option::Option<ChainKey>,
    #[prost(message, repeated, tag = "3")]
    pub message_keys: ::prost::alloc::vec::Vec<MessageKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainKey {
    #[prost(uint32, tag = "1")]
    pub counter: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageKey {
    #[prost(uint32, tag = "1")]
    pub counter: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingPreKey {
    #[prost(uint32, optional, tag = "1")]
    pub prekey_id: ::core::option::Option<u32>,
    #[prost(uint32, tag = "2")]
    pub signed_prekey_id: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub base_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionMetadata {
    #[prost(uint64, tag = "1")]
    pub created_at: u64,
    #[prost(uint64, tag = "2")]
    pub last_used: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreKeyRecord {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedPreKeyRecord {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdentityKeyPair {
    #[prost(bytes = "vec", tag = "1")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderKeyState {
    #[prost(uint32, tag = "1")]
    pub chain_id: u32,
    #[prost(message, optional, tag = "2")]
    pub sender_chain_key: ::core::option::Option<SenderChainKey>,
    #[prost(message, optional, tag = "3")]
    pub sender_signing_key: ::core::option::Option<SenderSigningKey>,
    #[prost(message, repeated, tag = "4")]
    pub sender_message_keys: ::prost::alloc::vec::Vec<SenderMessageKey>,
    #[prost(uint32, tag = "5")]
    pub message_version: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderChainKey {
    #[prost(uint32, tag = "1")]
    pub iteration: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderMessageKey {
    #[prost(uint32, tag = "1")]
    pub iteration: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderSigningKey {
    #[prost(bytes = "vec", tag = "1")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderKeyRecord {
    #[prost(message, repeated, tag = "1")]
    pub sender_key_states: ::prost::alloc::vec::Vec<SenderKeyState>,
}
