// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhisperMessage {
    #[prost(bytes="vec", optional, tag="1")]
    pub ephemeral_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag="2")]
    pub counter: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub previous_counter: ::core::option::Option<u32>,
    /// PushMessageContent
    #[prost(bytes="vec", optional, tag="4")]
    pub ciphertext: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreKeyWhisperMessage {
    #[prost(uint32, optional, tag="5")]
    pub registration_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="1")]
    pub pre_key_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="6")]
    pub signed_pre_key_id: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="2")]
    pub base_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="3")]
    pub identity_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// WhisperMessage
    #[prost(bytes="vec", optional, tag="4")]
    pub message: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyExchangeMessage {
    #[prost(uint32, optional, tag="1")]
    pub id: ::core::option::Option<u32>,
    #[prost(bytes="vec", optional, tag="2")]
    pub base_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="3")]
    pub ephemeral_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="4")]
    pub identity_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="5")]
    pub base_key_signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
